<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPptmxhv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPptmxhv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPptmxhv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPptmxhv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPptmxhv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pptmxhv',
    'container.build_id' => 'd7a45859',
    'container.build_time' => 1613690405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPptmxhv');
