<?php

namespace ContainerOmtm1dA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StockController' shared autowired service.
     *
     * @return \App\Controller\StockController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StockController.php';

        $container->services['App\\Controller\\StockController'] = $instance = new \App\Controller\StockController(($container->privates['App\\Repository\\StockRepository'] ?? $container->load('getStockRepositoryService')), ($container->privates['App\\Repository\\BookRepository'] ?? $container->load('getBookRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\StockController', $container));

        return $instance;
    }
}
